name: Prettier

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettier Checker
        uses: creyD/prettier_action@v3.1
        with:
          args: --check --log-level=warn .
